[package]
name = "conventional_commits_linter"
version = "0.7.2"
description = "A tooling and language agnostic Git commit linter for the Conventional Commits specification."
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2018"
license = "AGPL-3.0"
repository = "https://gitlab.com/DeveloperC/conventional_commits_linter"
readme = "README.md"
keywords = ["conventional", "commits", "lint", "linting", "git"]
categories = ["command-line-utilities", "development-tools"]


[dependencies]
git2 = { version = "0.13.17", default-features = false, features=[] }
log = "0.4.14"
pretty_env_logger = "0.4.0"
semver = "0.11.0"
regex = "1.4.3"
lazy_static = "1.4.0"
structopt = "0.3.21"
console = "0.14.0"


[dev-dependencies]
rstest = "0.6.4"


[profile.release]
lto = 'fat'
codegen-units = 1
