[workspace]

members = [
    "conventional_commits_linter",
    "conventional_commits_linter_lib",
]


[patch.crates-io]
conventional_commits_linter_lib = { path = "conventional_commits_linter_lib" }


[profile.release]
lto = 'fat'
codegen-units = 1
