[package]
name = "conventional_commits_linter"
version = "0.6.2"
description = "A fast and sensible linter for the Conventional Commits v1.0.0 format. Which catches violations other linters do not combined with no dependencies on specific tools or interpreter languages."
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2018"
license = "AGPL-3.0"
repository = "https://gitlab.com/DeveloperC/conventional_commits_linter"
readme = "README.md"
keywords = ["conventional", "commits", "lint", "linting", "git"]
categories = ["command-line-utilities", "development-tools"]


[dependencies]
git2 = "0.13.12"
log = "0.4.11"
pretty_env_logger = "0.4.0"
semver = "0.11.0"
regex = "1.4.2"
lazy_static = "1.4.0"
structopt = "0.3.20"
console = "0.13.0"


[dev-dependencies]
rstest = "0.6.4"
