[package]
name = "conventional_commits_linter"
version = "0.2.0"
description = "A utility to lint Git commit messages against the Convectional Commits v1.0.0 format."
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://gitlab.com/DeveloperC/conventional_commits_linter"
readme = "README.md"
keywords = ["conventional", "commits", "lint", "linting", "git"]
categories = ["command-line-utilities", "development-tools"]


[dependencies]
git2 = "0.13.8"
log = "0.4.11"
pretty_env_logger = "0.4.0"
semver = "0.10.0"
regex = "1.3.9"
lazy_static = "1.4.0"
structopt = "0.3.15"


[dev-dependencies]
rstest = "0.6.4"
