name: Dogfood

on: pull_request

permissions:
  contents: read

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Dogfooding Docker
        run: make dogfood-docker FROM="origin/${{ github.base_ref }}"
  github-actions:
    name: GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Download binary
        run: |
          # x-release-please-start-version
          version="v1.0.4" && wget -O - "https://github.com/DeveloperC286/conventional_commits_linter/releases/download/${version}/x86_64-unknown-linux-musl.tar.gz" | tar xz --directory "/usr/bin/"
          # x-release-please-end
      - name: Lint commits
        run: conventional_commits_linter --from-reference "origin/${{ github.base_ref }}" --allow-angular-type-only
