name: Dogfood

on: pull_request

permissions:
  contents: read

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Dogfooding Docker
        run: make dogfood-docker FROM="origin/${{ github.base_ref }}"
  github-actions:
    name: GitHub Actions
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/developerc286/conventional_commits_linter:0.16.0
    steps:
      - name: Checkout code.
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Lint commits
        run: conventional_commits_linter --commit-type angular "origin/${{ github.base_ref }}"
